import "../../../styles/table.css";

export const Table = () => {
  return (
    <table>
      <tr>
        <th>День</th>
        <th>HDFS/ruid</th>
        <th>HDFS/gruid</th>
        <th>Bacon/ruid</th>
        <th>Bacon/gruid</th>
        <th>Bacon/elastic</th>
        <th>Bacon/SSP/elastic</th>
      </tr>
      <tr>
        <td>2023-03-20</td>
        <td>3592923</td>
        <td>646451</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>2023-03-20</td>
        <td>3592923</td>
        <td>646451</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>2023-03-20</td>
        <td>3592923</td>
        <td>646451</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>2023-03-20</td>
        <td>3592923</td>
        <td>646451</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>2023-03-20</td>
        <td>3592923</td>
        <td>646451</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
      </tr>
      <tr>
        <td>2023-03-20</td>
        <td>3592923</td>
        <td>646451</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
        <td>-</td>
      </tr>
    </table>
  );
};
